### PR TITLE
Added locations file for remote updates

### PR DESCRIPTION
**Pull request by pm66**
Adding file "aboveLabel.txt" allows central maintenance of locations settings.
See the SpineOMatic documentation on settings for label prefixes:

Label Prefixes Panel
https://github.com/ExLibrisGroup/SpineOMatic/wiki/Setup-Panels#label-prefixes-panel

### CODE REVIEW

**Review by cappadona — COMMENTED** [review]
Thanks @pm66 . Will you please make note of the URL that should be used in SpineOMatic in order to retrieve this shared file?

**Comment by pm66** [comment]
Should I just add a note in the main README.md ?

**Comment by cappadona** [comment]
I was thinking a note/comment here in the PR discussion as a start, but it would be great to have the README updated as well to point to our local SOM documentation.

If that doesn't yet exist, and we don't have a planned home, then perhaps you're open to a new issue to document this within the repo?

**Comment by pm66** [comment]
Okay, so for right now, I'll just note it here and then add an issue for documentation.  The URL in the SOM label prefix settings should point to the folder containing the file; SOM adds the file name.  
      https://raw.githubusercontent.com/cul-it/setae-api/main/app/  

I've tested it from here: https://raw.githubusercontent.com/cul-it/setae-api/pm66_locations_file/app/   It works with or without the final slash.  It's nice that it checks the file when the user starts the application, they don't even have to know to check for updates.

**Comment by pm66** [comment]
Does this seem okay to pull?

**Review by cappadona — APPROVED** [review]
@pm66 Go for it! Sorry about the delay.

**Pull request merged**
